### ISSUE TITLE
Loved it!

### ISSUE THREAD

**Issue by OrkoHunter** [plibither8/2048.cpp#1]
I enjoyed the game and spent a good chunk of my work time making up to 1024. 😄 
Just wanted to say Kudos. :)
<img width="603" alt="screen shot 2018-07-11 at 3 30 34 pm" src="https://user-images.githubusercontent.com/8065913/42602730-98dc197e-851f-11e8-977c-c8e17f5249fa.png">

**Comment by plibither8** [comment]
Thanks a lot! :smile:
