### ISSUE TITLE
[Suggestion] `Time taken` can be more readable

### ISSUE THREAD

**Issue by comwrg** [plibither8/2048.cpp#13]
```
  STATISTICS
  ----------
  Final score:       11408
  Largest Tile:      1024
  Number of moves:   692
  Time taken:        1068.8 seconds
```
I think `Time taken` change to  xx Hours xx Minutes xx Seconds can be  more acceptable by human beings.

**Comment by plibither8** [comment]
That's a nice suggestion, I'll look into it. Thank you :)

**Comment by plibither8** [comment]
I consider this done, thanks!
