### ISSUE TITLE
New ci failure

### ISSUE THREAD

**Issue by scivision** [plibither8/2048.cpp#131]
Sorry about the CI failure on the new github actions. I know it went wrong and I'll make a new PR to fix it in the next couple days thank you.

**Comment by tcoyvwac** [comment]
No problem, @scivision, your contributions are much appreciated! :smile_cat:

**Comment by scivision** [comment]
This is fixed in #130 along with adding windows test

**Comment by tcoyvwac** [comment]
Closing issue as #130 fix has been merged in. Feel free to reopen if any discussions + updates needed.
Thanks for your quick efforts @scivision ! :joy_cat: :+1: Feel free to of course contribute again!
