### ISSUE TITLE
Odd Character Display

### ISSUE THREAD

**Issue by DeveloperPaul123** [plibither8/2048.cpp#20]
## Platform 
- Windows 10, MSVC 2017
- Commit: 71e62371b9f1a8084c52568f8167df42352c0c7f

## Issue:
- Just pulled to the latest commit on master and the game now looks like this:
![image](https://user-images.githubusercontent.com/6591180/45248731-35848e00-b2e3-11e8-9d10-f1fb99bc9b1a.png)
- Additionally I always get the message `'clear' is not recognized as an internal or external command, operable program or batch file`

**Comment by plibither8** [comment]
I guess your best bet is to use a terminal that supports unix commands. The 'odd character' are box-drawing characters which your terminal does not support and hence renders those weird characters. The clear command is not supported by your terminal too.

For Windows, I recommend Git Bash, Cygwin or Hyper terminal. They offer a nice unix-like environment to work with.

**Comment by DeveloperPaul123** [comment]
@plibither8 Great thanks for the clarification.
