### ISSUE TITLE
Better demo gif for README

### ISSUE THREAD

**Issue by plibither8** [plibither8/2048.cpp#23]
The current demo gif on the repository's README page is alright, but it looks ugly when compared to the beautiful terminal gifs I have seen on other repositories (eg. Sindre Sorhus's repos). Anyone who can create a better gif than the current one, showcasing most of the features of the game (make sure to do a `git pull`), I'd be obliged. Thanks!

**Comment by felixhaeberle** [comment]
I would create some with https://carbon.now.sh or GIPHY showing the main game principles and how to play in a nice looking way.

**Comment by plibither8** [comment]
@plibither8 Great!

**Comment by kukac7** [comment]
sry, I just compressed it. 😞 #45

**Comment by plibither8** [comment]
@felixhaeberle What's the progress? :smile:

**Comment by felixhaeberle** [comment]
@plibither8 I try to do it tonight! stay tuned

**Comment by plibither8** [comment]
Hey @felixhaeberle, hate to bother you so much! Just a ping 😅
