### ISSUE TITLE
Project should use gitflow repository management

### ISSUE THREAD

**Issue by cawvyoct** [plibither8/2048.cpp#27]
Gitflow-style repos [[1]](https://nvie.com/posts/a-successful-git-branching-model/) requires a `develop` branch. 

All forked project's `x-feature` branches aim to merge with `upstream`'s `develop` branch. The `upstream`'s repo owner can then merge to the `upstream`'s `master` branch when "safe and ready" to do so.
 This method of source-code management may prevent severe merge problems / conflicts in the future.

1: https://nvie.com/posts/a-successful-git-branching-model/

**Comment by plibither8** [comment]
This seems very reasonable and should be implemented. How must it work though, I'm new to this. Will PRs be made directly of the develop branch?

**Comment by cawvyoct** [comment]
> Will PRs be made directly of the develop branch?

Yes, by default. The `master` branch more like a read-only protected branch.

_(I do not know Github's project management system so I cannot help you on how to set this up, sorry!)_

**Comment by plibither8** [comment]
Ah alright. Thanks a lot for the suggestion, I'll read more about this and see how I can set it up. I'll be keeping this issue open for a while.

**Comment by cxong** [comment]
Gitflow is best if there are long-lived development features that are not ready for release. For small teams it is simpler to use trunk based development. Please compare the different models before jumping into this.
https://trunkbaseddevelopment.com/alternative-branching-models/
