### ISSUE TITLE
Better directory structure for project

### ISSUE THREAD

**Issue by plibither8** [plibither8/2048.cpp#30]
I feel like the current structure of files and directories is inefficient and not clean. There should be better management of the source files and the build files, rather than all of them being in the root directory.

I am comparatively inexperienced with how larger C++ projects handle directory management. It would be great if a better management is suggested, and better yet, I'd welcome all PRs that implement such a structure. Thanks.

**Comment by jhugobb** [comment]
I can take this one :+1:

**Comment by plibither8** [comment]
Great, thanks!
