### ISSUE TITLE
Replace enum with enum class

### ISSUE THREAD

**Issue by tiendq** [plibither8/2048.cpp#65]
`enum class` is a new C++ 11 feature and it has several advantages over `enum`, more detail here https://isocpp.org/wiki/faq/cpp11-language-types#enum-class

I fixed `Color` (#62) but later found more in other places. It isn't high priority but a good reason for refactoring code :)

**Comment by VinceBackpack** [comment]
I'll work on it.

**Comment by Chris99999** [comment]
I take this work!
