### ISSUE TITLE
Allow user to go back to main menu when choosing game board size

### ISSUE THREAD

**Issue by tiendq** [plibither8/2048.cpp#68]
Basically user can go back to menu at anytime and can choose to exit application nicely instead of `Ctrl+C`.

**Comment by plibither8** [comment]
How will the flow work? When the user is choosing the board size, the available 'input' is only the board size input. How will they signal for an exit?

**Comment by tiendq** [comment]
Add “(0 to go back)” :)

**Comment by plibither8** [comment]
Hmm, seems feasible.

More such features are increasing the need for the program to handle user interactions in a better way. This just makes me wonder: is using `ncurses` the right way to go henceforth, ie., is it worth it?

**Comment by cawvyoct** [comment]
`ncurses` for now is not needed. 
 Cleaning up (refactoring) of code design is needed before `ncurses` should be added to the codebase. As this is a good learner project, I think caution should be used before adding new libraries.

**Comment by tcoyvwac** [comment]
PR #106 fixes this Issue.
This Issue will be closed unless the situation changes.
