### ISSUE TITLE
Character `1` being printed

### ISSUE THREAD

**Issue by christianbundy** [plibither8/2048.cpp#9]
I'm not sure why, but the character `1` keeps getting printed to the console for me. I'm using Zsh and GNOME Terminal. For example:

```
1   /\\\\\\\\\          /\\\\\\\                /\\\         /\\\\\\\\\    1
1  /\\\///////\\\      /\\\/////\\\            /\\\\\       /\\\///////\\\  1
1  \///      \//\\\    /\\\    \//\\\         /\\\/\\\      \/\\\     \/\\\  1
1             /\\\/    \/\\\     \/\\\       /\\\/\/\\\      \///\\\\\\\\\/   1
1           /\\\//      \/\\\     \/\\\     /\\\/  \/\\\       /\\\///////\\\  1
1         /\\\//         \/\\\     \/\\\   /\\\\\\\\\\\\\\\\   /\\\      \//\\\ 1
1        /\\\/            \//\\\    /\\\   \///////////\\\//   \//\\\      /\\\  1
1        /\\\\\\\\\\\\\\\   \///\\\\\\\/              \/\\\      \///\\\\\\\\\/   1
1        \///////////////      \///////                \///         \/////////     1



1  Welcome to 2048!1

          1. Play a New Game
          2. View Highscores and Statistics

  Enter Choice: 

```

Any ideas why this might be happening?

**Comment by christianbundy** [comment]
Looks like this may be caused by `bold_on` and `bold_off` -- I'll continue investigating.

**Comment by pdevine** [comment]
Seeing the same thing.

**Comment by jagger27** [comment]
I was able to fix this by deleting the bold_on and bold_off definitions and adding 
```
#define bold_on "\e[1m"
#define bold_off "\e[0m"
```
to global.h

**Comment by plibither8** [comment]
Hmm, this shouldn't be happening (of course). How should approach this issue? @jagger27 @christianbundy

**Comment by plibither8** [comment]
#10 fixes this. 
https://github.com/plibither8/2048.cpp/commit/7b1b1600f04b1a6502a2f3967f0cb3957b7a0dcc

**Comment by christianbundy** [comment]
Yep, it looks like #10 resolves the issue on the game board but the high scores and statistics still seem to be using the old bold code. Would you mind re-opening?
